on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server:  ftp.pharmalife-ye.com
        username: site@pharmalife-ye.com
        #password: ${{ secrets.ftp_password }}
        password: 1hT-1B1[Gh}+
